/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#3873b6',
        'on-secondary': '#393000',
        'on-secondary-container': '#e5d173',
        'secondary-fixed': '#f7e382',
        'on-secondary-fixed': '#211b00',
        'on-tertiary-container': '#f4f6ff',
        'outline-variant': '#5c403b',
        'secondary-container': '#675900',
        'error-container': '#93000a',
        'tertiary-fixed': '#d3e3ff',
        'on-surface-variant': '#e6bdb7',
        'on-primary': '#690000',
        'primary-container': '#da291c',
        'surface-tint': '#ffb4a8',
        'on-primary-fixed': '#410000',
        'on-tertiary-fixed-variant': '#004882',
        'surface-container-high': '#272a32',
        'surface-bright': '#363941',
        'surface-container-highest': '#32353d',
        'on-error': '#690005',
        'primary-fixed-dim': '#ffb4a8',
        'on-primary-fixed-variant': '#930001',
        'on-background': '#e1e2ec',
        'surface-dim': '#10131a',
        'surface-variant': '#32353d',
        'tertiary-fixed-dim': '#a3c9ff',
        background: '#10131a',
        'inverse-on-surface': '#2d3038',
        'on-error-container': '#ffdad6',
        error: '#ffb4ab',
        'primary-fixed': '#ffdad4',
        'on-tertiary-fixed': '#001c39',
        'on-surface': '#e1e2ec',
        'inverse-surface': '#e1e2ec',
        tertiary: '#a3c9ff',
        outline: '#ac8883',
        'surface-container-low': '#191b23',
        surface: '#10131a',
        primary: '#ffb4a8',
        'on-tertiary': '#00315c',
        secondary: '#dac769',
        'inverse-primary': '#be0f09',
        'surface-container': '#1d1f27',
        'on-secondary-fixed-variant': '#524700',
        'surface-container-lowest': '#0b0e15',
        'secondary-fixed-dim': '#dac769',
        'on-primary-container': '#fff5f3',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'container-max': '1200px',
        gutter: '16px',
        unit: '8px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        'display-lg': ['Archivo Narrow'],
        'body-sm': ['Hanken Grotesk'],
        'headline-lg-mobile': ['Archivo Narrow'],
        'headline-lg': ['Archivo Narrow'],
        'label-caps': ['Hanken Grotesk'],
        'title-md': ['Archivo Narrow'],
        'body-lg': ['Hanken Grotesk'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'title-md': ['20px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
